CREATE DATABASE CADPRODUTO

CREATE TABLE PRODUTOS(
	CODIGO		VARCHAR(6)	NOT NULL,		/*CÓDIGO DO PRODUTO*/
	NOME		VARCHAR(20) NOT NULL,		/*NOME DO PRODUTO*/
	UNIMEDIDA	VARCHAR(3)	NOT NULL,		/*UNIDADE DE MEDIDA*/
	PRECOPAD	FLOAT		NULL,			/*PREÇO PADRÃO*/
	DESCONTOMAX INT			NULL,			/*DESCONTO MÁXIMO*/
	PRIMARY KEY(CODIGO)
)